services:
  mockserver:
    image: mockserver/mockserver:5.15.0
    container_name: mockserver
    ports:
      - "1080:1080"
    environment:
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/init.json
      MOCKSERVER_WATCH_INITIALIZATION_JSON: "true"
    volumes:
      - ./mockserver:/config
    networks:
      - demo-load

  jaeger:
    image: jaegertracing/all-in-one:1.57
    ports:
      - "16686:16686"
      - "4318:4318"
    environment:
      - LOG_LEVEL=debug
    networks:
      - demo-load

networks:
  demo-load:
    external: true